CREATE DATABASE DB_AGENDA
GO

USE DB_AGENDA
GO

CREATE TABLE TB_CONTATO
(
  ID_CONTATO INT IDENTITY NOT NULL
 ,NM_CONTATO VARCHAR(255) NOT NULL
 ,NR_TEL_CONTATO VARCHAR(20) NOT NULL
 ,CONSTRAINT PK_TB_CONTATO PRIMARY KEY(ID_CONTATO) 
)


SELECT *
FROM TB_CONTATO